# Generated by Django 4.2.29 on 2026-04-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='day_of_week',
            field=models.CharField(choices=[('Mon', 'Понедельник'), ('Tue', 'Вторник'), ('Wed', 'Среда'), ('Thu', 'Четверг'), ('Fri', 'Пятница'), ('Sat', 'Суббота'), ('Sun', 'Воскресенье')], default='Mon', max_length=3),
        ),
        migrations.AddField(
            model_name='group',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
